version:  '3.5'

networks:
  backend:
    driver: bridge

services:
  sisovid_api:
    build: ./sisovid-api/
    container_name: sisovid_api
    working_dir: /app
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./sisovid-api:/app
      - /app/vendor
    ports:
      - "8010"
    environment:
      WAIT_HOSTS_TIMEOUT: 120
    restart: on-failure
    stdin_open: true
    networks:
      - backend
  nginx:
    build: 
      context: ./sisovid-client
      dockerfile: Dockerfile
    container_name: sisovid_nginx
    networks:
      - backend
    ports:
      - "8010"
      - "80"
    links:
      - sisovid_api
    depends_on:
      - sisovid_api
