version:  '3.5'

networks:
  backend:
    driver: bridge

services:
  sisovid_api:
    build: ./sisovid-api/
    container_name: sisovid_api
    working_dir: /app
    command: sh -c '/etc/init.d/nginx start && php -S 0.0.0.0:8020 -t public'
    volumes:
      - ./sisovid-api:/app
      - /app/vendor
    ports:
      - "8010:8020"
    environment:
      WAIT_HOSTS_TIMEOUT: 120
    restart: on-failure
    stdin_open: true
    networks:
      - backend
  nginx:
    build: 
      context: ./sisovid-client
      dockerfile: Dockerfile
    container_name: sisovid_nginx
    networks:
      - backend
    ports:
      - "80:80"
    #labels:  
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.nginx.entrypoints=websecure"
    #  - "traefik.http.routers.nginx.rule=Host(`test1.lagocha2020.com`)"
    #  - "traefik.http.routers.nginx.tls.certresolver=lets-encr"
    links:
      - sisovid_api
    depends_on:
      - sisovid_api
