<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertCountries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $data = [
            ['name' => 'AFGANISTÁN'],
            ['name' => 'ISLAS GLAND'],
            ['name' => 'ALBANIA'],
            ['name' => 'ALEMANIA'],
            ['name' => 'ANDORRA'],
            ['name' => 'ANGOLA'],
            ['name' => 'ANGUILLA'],
            ['name' => 'ANTÁRTIDA'],
            ['name' => 'ANTIGUA Y BARBUDA'],
            ['name' => 'ANTILLAS HOLANDESAS'],
            ['name' => 'ARABIA SAUDÍ'],
            ['name' => 'ARGELIA'],
            ['name' => 'ARGENTINA'],
            ['name' => 'ARMENIA'],
            ['name' => 'ARUBA'],
            ['name' => 'AUSTRALIA'],
            ['name' => 'AUSTRIA'],
            ['name' => 'AZERBAIYÁN'],
            ['name' => 'BAHAMAS'],
            ['name' => 'BAHRÉIN'],
            ['name' => 'BANGLADESH'],
            ['name' => 'BARBADOS'],
            ['name' => 'BIELORRUSIA'],
            ['name' => 'BÉLGICA'],
            ['name' => 'BELICE'],
            ['name' => 'BENIN'],
            ['name' => 'BERMUDAS'],
            ['name' => 'BHUTÁN'],
            ['name' => 'BOLIVIA'],
            ['name' => 'BOSNIA Y HERZEGOVINA'],
            ['name' => 'BOTSUANA'],
            ['name' => 'ISLA BOUVET'],
            ['name' => 'BRASIL'],
            ['name' => 'BRUNÉI'],
            ['name' => 'BULGARIA'],
            ['name' => 'BURKINA FASO'],
            ['name' => 'BURUNDI'],
            ['name' => 'CABO VERDE'],
            ['name' => 'ISLAS CAIMÁN'],
            ['name' => 'CAMBOYA'],
            ['name' => 'CAMERÚN'],
            ['name' => 'CANADÁ'],
            ['name' => 'REPÚBLICA CENTROAFRICANA'],
            ['name' => 'CHAD'],
            ['name' => 'REPÚBLICA CHECA'],
            ['name' => 'CHILE'],
            ['name' => 'CHINA'],
            ['name' => 'CHIPRE'],
            ['name' => 'ISLA DE NAVIDAD'],
            ['name' => 'CIUDAD DEL VATICANO'],
            ['name' => 'ISLAS COCOS'],
            ['name' => 'COLOMBIA'],
            ['name' => 'COMORAS'],
            ['name' => 'REPÚBLICA DEMOCRÁTICA DEL CONGO'],
            ['name' => 'CONGO'],
            ['name' => 'ISLAS COOK'],
            ['name' => 'COREA DEL NORTE'],
            ['name' => 'COREA DEL SUR'],
            ['name' => 'COSTA DE MARFIL'],
            ['name' => 'COSTA RICA'],
            ['name' => 'CROACIA'],
            ['name' => 'CUBA'],
            ['name' => 'DINAMARCA'],
            ['name' => 'DOMINICA'],
            ['name' => 'REPÚBLICA DOMINICANA'],
            ['name' => 'ECUADOR'],
            ['name' => 'EGIPTO'],
            ['name' => 'EL SALVADOR'],
            ['name' => 'EMIRATOS ÁRABES UNIDOS'],
            ['name' => 'ERITREA'],
            ['name' => 'ESLOVAQUIA'],
            ['name' => 'ESLOVENIA'],
            ['name' => 'ESPAÑA'],
            ['name' => 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS'],
            ['name' => 'ESTADOS UNIDOS'],
            ['name' => 'ESTONIA'],
            ['name' => 'ETIOPÍA'],
            ['name' => 'ISLAS FEROE'],
            ['name' => 'FILIPINAS'],
            ['name' => 'FINLANDIA'],
            ['name' => 'FIYI'],
            ['name' => 'FRANCIA'],
            ['name' => 'GABÓN'],
            ['name' => 'GAMBIA'],
            ['name' => 'GEORGIA'],
            ['name' => 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR'],
            ['name' => 'GHANA'],
            ['name' => 'GIBRALTAR'],
            ['name' => 'GRANADA'],
            ['name' => 'GRECIA'],
            ['name' => 'GROENLANDIA'],
            ['name' => 'GUADALUPE'],
            ['name' => 'GUAM'],
            ['name' => 'GUATEMALA'],
            ['name' => 'GUAYANA FRANCESA'],
            ['name' => 'GUINEA'],
            ['name' => 'GUINEA ECUATORIAL'],
            ['name' => 'GUINEA-BISSAU'],
            ['name' => 'GUYANA'],
            ['name' => 'HAITÍ'],
            ['name' => 'ISLAS HEARD Y MCDONALD'],
            ['name' => 'HONDURAS'],
            ['name' => 'HONG KONG'],
            ['name' => 'HUNGRÍA'],
            ['name' => 'INDIA'],
            ['name' => 'INDONESIA'],
            ['name' => 'IRÁN'],
            ['name' => 'IRAQ'],
            ['name' => 'IRLANDA'],
            ['name' => 'ISLANDIA'],
            ['name' => 'ISRAEL'],
            ['name' => 'ITALIA'],
            ['name' => 'JAMAICA'],
            ['name' => 'JAPÓN'],
            ['name' => 'JORDANIA'],
            ['name' => 'KAZAJSTÁN'],
            ['name' => 'KENIA'],
            ['name' => 'KIRGUISTÁN'],
            ['name' => 'KIRIBATI'],
            ['name' => 'KUWAIT'],
            ['name' => 'LAOS'],
            ['name' => 'LESOTHO'],
            ['name' => 'LETONIA'],
            ['name' => 'LÍBANO'],
            ['name' => 'LIBERIA'],
            ['name' => 'LIBIA'],
            ['name' => 'LIECHTENSTEIN'],
            ['name' => 'LITUANIA'],
            ['name' => 'LUXEMBURGO'],
            ['name' => 'MACAO'],
            ['name' => 'ARY MACEDONIA'],
            ['name' => 'MADAGASCAR'],
            ['name' => 'MALASIA'],
            ['name' => 'MALAWI'],
            ['name' => 'MALDIVAS'],
            ['name' => 'MALÍ'],
            ['name' => 'MALTA'],
            ['name' => 'ISLAS MALVINAS'],
            ['name' => 'ISLAS MARIANAS DEL NORTE'],
            ['name' => 'MARRUECOS'],
            ['name' => 'ISLAS MARSHALL'],
            ['name' => 'MARTINICA'],
            ['name' => 'MAURICIO'],
            ['name' => 'MAURITANIA'],
            ['name' => 'MAYOTTE'],
            ['name' => 'MÉXICO'],
            ['name' => 'MICRONESIA'],
            ['name' => 'MOLDAVIA'],
            ['name' => 'MÓNACO'],
            ['name' => 'MONGOLIA'],
            ['name' => 'MONTSERRAT'],
            ['name' => 'MOZAMBIQUE'],
            ['name' => 'MYANMAR'],
            ['name' => 'NAMIBIA'],
            ['name' => 'NAURU'],
            ['name' => 'NEPAL'],
            ['name' => 'NICARAGUA'],
            ['name' => 'NÍGER'],
            ['name' => 'NIGERIA'],
            ['name' => 'NIUE'],
            ['name' => 'ISLA NORFOLK'],
            ['name' => 'NORUEGA'],
            ['name' => 'NUEVA CALEDONIA'],
            ['name' => 'NUEVA ZELANDA'],
            ['name' => 'OMÁN'],
            ['name' => 'PAÍSES BAJOS'],
            ['name' => 'PAKISTÁN'],
            ['name' => 'PALAU'],
            ['name' => 'PALESTINA'],
            ['name' => 'PANAMÁ'],
            ['name' => 'PAPÚA NUEVA GUINEA'],
            ['name' => 'PARAGUAY'],
            ['name' => 'PERÚ'],
            ['name' => 'ISLAS PITCAIRN'],
            ['name' => 'POLINESIA FRANCESA'],
            ['name' => 'POLONIA'],
            ['name' => 'PORTUGAL'],
            ['name' => 'PUERTO RICO'],
            ['name' => 'QATAR'],
            ['name' => 'REINO UNIDO'],
            ['name' => 'REUNIÓN'],
            ['name' => 'RUANDA'],
            ['name' => 'RUMANIA'],
            ['name' => 'RUSIA'],
            ['name' => 'SAHARA OCCIDENTAL'],
            ['name' => 'ISLAS SALOMÓN'],
            ['name' => 'SAMOA'],
            ['name' => 'SAMOA AMERICANA'],
            ['name' => 'SAN CRISTÓBAL Y NEVIS'],
            ['name' => 'SAN MARINO'],
            ['name' => 'SAN PEDRO Y MIQUELÓN'],
            ['name' => 'SAN VICENTE Y LAS GRANADINAS'],
            ['name' => 'SANTA HELENA'],
            ['name' => 'SANTA LUCÍA'],
            ['name' => 'SANTO TOMÉ Y PRÍNCIPE'],
            ['name' => 'SENEGAL'],
            ['name' => 'SERBIA Y MONTENEGRO'],
            ['name' => 'SEYCHELLES'],
            ['name' => 'SIERRA LEONA'],
            ['name' => 'SINGAPUR'],
            ['name' => 'SIRIA'],
            ['name' => 'SOMALIA'],
            ['name' => 'SRI LANKA'],
            ['name' => 'SUAZILANDIA'],
            ['name' => 'SUDÁFRICA'],
            ['name' => 'SUDÁN'],
            ['name' => 'SUECIA'],
            ['name' => 'SUIZA'],
            ['name' => 'SURINAM'],
            ['name' => 'SVALBARD Y JAN MAYEN'],
            ['name' => 'TAILANDIA'],
            ['name' => 'TAIWÁN'],
            ['name' => 'TANZANIA'],
            ['name' => 'TAYIKISTÁN'],
            ['name' => 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO'],
            ['name' => 'TERRITORIOS AUSTRALES FRANCESES'],
            ['name' => 'TIMOR ORIENTAL'],
            ['name' => 'TOGO'],
            ['name' => 'TOKELAU'],
            ['name' => 'TONGA'],
            ['name' => 'TRINIDAD Y TOBAGO'],
            ['name' => 'TÚNEZ'],
            ['name' => 'ISLAS TURCAS Y CAICOS'],
            ['name' => 'TURKMENISTÁN'],
            ['name' => 'TURQUÍA'],
            ['name' => 'TUVALU'],
            ['name' => 'UCRANIA'],
            ['name' => 'UGANDA'],
            ['name' => 'URUGUAY'],
            ['name' => 'UZBEKISTÁN'],
            ['name' => 'VANUATU'],
            ['name' => 'VENEZUELA'],
            ['name' => 'VIETNAM'],
            ['name' => 'ISLAS VÍRGENES BRITÁNICAS'],
            ['name' => 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS'],
            ['name' => 'WALLIS Y FUTUNA'],
            ['name' => 'YEMEN'],
            ['name' => 'YIBUTI'],
            ['name' => 'ZAMBIA'],
            ['name' => 'ZIMBABUE'],
            ['name' => 'S/D'],
            ['name' => 'OTRO'],
        ];

        DB::table('countries')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
