<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertNationalities extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $data = [
            ['name' => 'AFGANA'],
            ['name' => 'ALBANESA'],
            ['name' => 'ALEMANA'],
            ['name' => 'ANDORRANA'],
            ['name' => 'ANGOLEÑA'],
            ['name' => 'ANTIGUANA'],
            ['name' => 'SAUDÍ'],
            ['name' => 'ARGELINA'],
            ['name' => 'ARGENTINA'],
            ['name' => 'ARMENIA'],
            ['name' => 'ARUBEÑA'],
            ['name' => 'AUSTRALIANA'],
            ['name' => 'AUSTRIACA'],
            ['name' => 'AZERBAIYANA'],
            ['name' => 'BAHAMEÑA'],
            ['name' => 'BANGLADESÍ'],
            ['name' => 'BARBADENSE'],
            ['name' => 'BAREINÍ'],
            ['name' => 'BELGA'],
            ['name' => 'BELICEÑA'],
            ['name' => 'BENINÉSA'],
            ['name' => 'BIELORRUSA'],
            ['name' => 'BIRMANA'],
            ['name' => 'BOLIVIANA'],
            ['name' => 'BOSNIA'],
            ['name' => 'BOTSUANA'],
            ['name' => 'BRASILEÑA'],
            ['name' => 'BRUNEANA'],
            ['name' => 'BÚLGARA'],
            ['name' => 'BURKINÉS'],
            ['name' => 'BURUNDÉSA'],
            ['name' => 'BUTANÉSA'],
            ['name' => 'CABOVERDIANA'],
            ['name' => 'CAMBOYANA'],
            ['name' => 'CAMERUNESA'],
            ['name' => 'CANADIENSE'],
            ['name' => 'CATARÍ'],
            ['name' => 'CHADIANA'],
            ['name' => 'CHILENA'],
            ['name' => 'CHINA'],
            ['name' => 'CHIPRIOTA'],
            ['name' => 'VATICANA'],
            ['name' => 'COLOMBIANA'],
            ['name' => 'COMORENSE'],
            ['name' => 'NORCOREANA'],
            ['name' => 'SURCOREANA'],
            ['name' => 'MARFILEÑA'],
            ['name' => 'COSTARRICENSE'],
            ['name' => 'CROATA'],
            ['name' => 'CUBANA'],
            ['name' => 'DANÉSA'],
            ['name' => 'DOMINIQUÉS'],
            ['name' => 'ECUATORIANA'],
            ['name' => 'EGIPCIA'],
            ['name' => 'SALVADOREÑA'],
            ['name' => 'EMIRATÍ'],
            ['name' => 'ERITREA'],
            ['name' => 'ESLOVACA'],
            ['name' => 'ESLOVENA'],
            ['name' => 'ESPAÑOLA'],
            ['name' => 'ESTADOUNIDENSE'],
            ['name' => 'ESTONIA'],
            ['name' => 'ETÍOPE'],
            ['name' => 'FILIPINA'],
            ['name' => 'FINLANDÉSA'],
            ['name' => 'FIYIANA'],
            ['name' => 'FRANCÉSA'],
            ['name' => 'GABONÉSA'],
            ['name' => 'GAMBIANA'],
            ['name' => 'GEORGIANA'],
            ['name' => 'GIBRALTAREÑA'],
            ['name' => 'GHANÉSA'],
            ['name' => 'GRANADINA'],
            ['name' => 'GRIEGA'],
            ['name' => 'GROENLANDÉSA'],
            ['name' => 'GUATEMALTECA'],
            ['name' => 'ECUATOGUINEANA'],
            ['name' => 'GUINEANA'],
            ['name' => 'GUINEANA'],
            ['name' => 'GUYANESA'],
            ['name' => 'HAITIANA'],
            ['name' => 'HONDUREÑA'],
            ['name' => 'HÚNGARA'],
            ['name' => 'HINDÚ'],
            ['name' => 'INDONESIA'],
            ['name' => 'IRAQUÍ'],
            ['name' => 'IRANÍ'],
            ['name' => 'IRLANDÉSA'],
            ['name' => 'ISLANDÉSA'],
            ['name' => 'COOKIANA'],
            ['name' => 'MARSHALÉSA'],
            ['name' => 'SALOMONENSE'],
            ['name' => 'ISRAELÍ'],
            ['name' => 'ITALIANA'],
            ['name' => 'JAMAIQUINA'],
            ['name' => 'JAPONÉSA'],
            ['name' => 'JORDANA'],
            ['name' => 'KAZAJA'],
            ['name' => 'KENIATA'],
            ['name' => 'KIRGUISA'],
            ['name' => 'KIRIBATIANA'],
            ['name' => 'KUWAITÍ'],
            ['name' => 'LAOSIANA'],
            ['name' => 'LESOTENSE'],
            ['name' => 'LETÓNA'],
            ['name' => 'LIBANÉSA'],
            ['name' => 'LIBERIANA'],
            ['name' => 'LIBIA'],
            ['name' => 'LIECHTENSTEINIANA'],
            ['name' => 'LITUANA'],
            ['name' => 'LUXEMBURGUÉSA'],
            ['name' => 'MALGACHE'],
            ['name' => 'MALASIA'],
            ['name' => 'MALAUÍ'],
            ['name' => 'MALDIVA'],
            ['name' => 'MALIENSE'],
            ['name' => 'MALTÉSA'],
            ['name' => 'MARROQUÍ'],
            ['name' => 'MARTINIQUÉS'],
            ['name' => 'MAURICIANA'],
            ['name' => 'MAURITANA'],
            ['name' => 'MEXICANA'],
            ['name' => 'MICRONESIA'],
            ['name' => 'MOLDAVA'],
            ['name' => 'MONEGASCA'],
            ['name' => 'MONGOLA'],
            ['name' => 'MONTENEGRINA'],
            ['name' => 'MOZAMBIQUEÑA'],
            ['name' => 'NAMIBIA'],
            ['name' => 'NAURUANA'],
            ['name' => 'NEPALÍ'],
            ['name' => 'NICARAGÜENSE'],
            ['name' => 'NIGERINA'],
            ['name' => 'NIGERIANA'],
            ['name' => 'NORUEGA'],
            ['name' => 'NEOZELANDÉSA'],
            ['name' => 'OMANÍ'],
            ['name' => 'NEERLANDÉSA'],
            ['name' => 'PAKISTANÍ'],
            ['name' => 'PALAUANA'],
            ['name' => 'PALESTINA'],
            ['name' => 'PANAMEÑA'],
            ['name' => 'PAPÚ'],
            ['name' => 'PARAGUAYA'],
            ['name' => 'PERUANA'],
            ['name' => 'POLACA'],
            ['name' => 'PORTUGUÉSA'],
            ['name' => 'PUERTORRIQUEÑA'],
            ['name' => 'BRITÁNICA'],
            ['name' => 'CENTROAFRICANA'],
            ['name' => 'CHECA'],
            ['name' => 'MACEDONIA'],
            ['name' => 'CONGOLEÑA'],
            ['name' => 'CONGOLEÑA'],
            ['name' => 'DOMINICANA'],
            ['name' => 'SUDAFRICANA'],
            ['name' => 'RUANDÉSA'],
            ['name' => 'RUMANA'],
            ['name' => 'RUSA'],
            ['name' => 'SAMOANA'],
            ['name' => 'CRISTOBALEÑA'],
            ['name' => 'SANMARINENSE'],
            ['name' => 'SANVICENTINA'],
            ['name' => 'SANTALUCENSE'],
            ['name' => 'SANTOTOMENSE'],
            ['name' => 'SENEGALÉSA'],
            ['name' => 'SERBIA'],
            ['name' => 'SEYCHELLENSE'],
            ['name' => 'SIERRALEONÉSA'],
            ['name' => 'SINGAPURENSE'],
            ['name' => 'SIRIA'],
            ['name' => 'SOMALÍ'],
            ['name' => 'CEILANÉSA'],
            ['name' => 'SUAZI'],
            ['name' => 'SURSUDANÉSA'],
            ['name' => 'SUDANÉSA'],
            ['name' => 'SUECA'],
            ['name' => 'SUIZA'],
            ['name' => 'SURINAMESA'],
            ['name' => 'TAILANDÉSA'],
            ['name' => 'TANZANA'],
            ['name' => 'TAYIKA'],
            ['name' => 'TIMORENSE'],
            ['name' => 'TOGOLÉSA'],
            ['name' => 'TONGANA'],
            ['name' => 'TRINITENSE'],
            ['name' => 'TUNECINA'],
            ['name' => 'TURCOMANA'],
            ['name' => 'TURCA'],
            ['name' => 'TUVALUANA'],
            ['name' => 'UCRANIANA'],
            ['name' => 'UGANDÉSA'],
            ['name' => 'URUGUAYA'],
            ['name' => 'UZBEKA'],
            ['name' => 'VANUATUENSE'],
            ['name' => 'VENEZOLANA'],
            ['name' => 'VIETNAMITA'],
            ['name' => 'YEMENÍ'],
            ['name' => 'YIBUTIANA'],
            ['name' => 'ZAMBIANA'],
            ['name' => 'ZIMBABUENSE'],
            ['name' => 'S/D'],
            ['name' => 'OTRO'],
        ];

        DB::table('nationalities')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
